CREATE TABLE IF NOT EXISTS users (
	id BIGINT PRIMARY KEY,
	orundum BIGINT NOT NULL DEFAULT 0,
	level BIGINT NOT NULL DEFAULT 1,
	xp BIGINT NOT NULL DEFAULT 0,
	xp_cards BIGINT NOT NULL DEFAULT 0,
	pity INT NOT NULL DEFAULT 0,
	chips BIGINT NOT NULL DEFAULT 0,
	stage BIGINT NOT NULL DEFAULT 0,
	max_stage BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS operators (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id BIGING NOT NULL,
	char_id VARCHAR(64) NOT NULL,
	level BIGINT NOT NULL DEFAULT 1,
	xp BIGINT NOT NULL DEFAULT 0,
	rank SMALLINT NOT NULL DEFAULT 0,
	favourited SMALLINT NOT NULL DEFAULT 0,
	FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS teams (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id BIGINT NOT NULL,
	field_unit INTEGER,
	support1 INTEGER,
	support2 INTEGER,
	support3 INTEGER,
	FOREIGN KEY(user_id) REFERENCES users(id),
	FOREIGN KEY(field_unit) REFERENCES operators(id),
	FOREIGN KEY(support1) REFERENCES operators(id),
	FOREIGN KEY(support2) REFERENCES operators(id),
	FOREIGN KEY(support3) REFERENCES operators(id)
);
